blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
#  아래에서 blog/ 부분은 이미 처리되고 넘어온 상황임
urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # # Example: /2012/11/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

    # # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # # Example: /2012/11/10/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # /blog/tag/ URL 요청을 처리할 뷰 클래스 지정, 태그 클라우드 출력용 뷰
    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # /blog/tag/태그 이름/ 요청을 처리할 뷰 클래스 지정
    # r'...': 이스케이프되지 않는 raw 스트링임을 표시
    # [^/]+ : / 이외 문자가 한번 이상 반복
    # (?u)  : 앞의 표현식을 유니코드로 인식하라고 지정(주소창에 한글 입력 가능하도록)
    # Example: /tag/tagname
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/  # ch09 1/1
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# static() 함수는 정적 파일 처리하는 뷰를 호출할 수 있도록 URL 패턴을 반환
from django.conf.urls.static import static                              # ch10 1/4
# settings 변수는 settings.py 모듈에서 정의한 항목들을 담고 있는 객체에 대한 참조
from django.conf import settings                                        # ch10 2/4

from mysite.views import HomeView
# 회원 가입 처리 뷰 임포트
from mysite.views import UserCreateView, UserCreateDoneTV               # ch11 1/2

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	# 아래 인증 관련 3행 추가                                           ch11 2/2
	# 장고 인증 URLconf를 인클루드하는데, 여기에 정의된 /login, /logout 등이
	# /accounts/login, /accounts/logout, /accounts/password_change/가 됨
	url(r'^accounts/', include('django.contrib.auth.urls')),
	# 계정 가입 처리하는 URL
	url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
	# 계정 가입 완료될 때 보여줄 URL
	url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),          # ch10 3/4

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)     # ch10 4/4
# 기존 urlpatterns에 static() 함수가 반환하는 URL 패턴을 추가
# static(prefix, view=django.views.static.serve, **kwargs)
# settings.MEDIA_URL = '/media/' 이런 URL 요청이 오면,
# django.views.static.serve() 뷰 함수가 처리하게 되어 있는데,
# 이 뷰 함수에 다음 인자를 전달함
# document_root = settings.MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

templates/base.html
<!DOCTYPE html>     <!--HTML5 규약을 준수하는 파일-->
<html lang="ko">    <!--언어는 한국어로 지정--><!---->

<head>              <!--페이지 타이틀과 css 파일 2개를 연결-->
<title>{% block title %}Grand Hotel{% endblock %}</title>

{% load staticfiles %}  <!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
<!--스타일시트 css/base.css 작성이 필요함-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Sunflower:300');
    </style>
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />


    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
    function initialize() {

     var Y_point = 33.249315; // Y 좌표
     var X_point = 126.408439; // X 좌표
     var zoomLevel = 17; // 첫 로딩시 보일 지도의 확대 레벨
     var markerTitle = "제주 그랜드 호텔"; // 현재 위치 마커에 마우스를 올렸을때 나타나는 이름
     var markerMaxWidth = 300; // 마커를 클릭했을때 나타나는 말풍선의 최대 크기

     // 말풍선 내용
     var contentString = '<div id="content">' +
     '<div id="siteNotice">' +
     '</div>' +
     '<h3 id="firstHeading" class="firstHeading">제주 그랜드 호텔</h3>' +
     '<div id="bodyContent">' +
     '<p>Jeju Island, 2812 색달동 서귀포시 Jejudo<br />' +
     'Tel. Tel 064-123-4567</p>' +
     '</div>' +
     '</div>';

     var myLatlng = new google.maps.LatLng(Y_point, X_point);
     var mapOptions = {
     zoom: zoomLevel,
     center: myLatlng,
     mapTypeId: google.maps.MapTypeId.ROADMAP
     }
     var map = new google.maps.Map(document.getElementById('map_view'), mapOptions);

     var marker = new google.maps.Marker({
     position: myLatlng,
     map: map,
     title: markerTitle
     });

     var infowindow = new google.maps.InfoWindow(
     {
     content: contentString,
     maxWidth: markerMaxWidth
     }
     );

     google.maps.event.addListener(marker, 'click', function() {
     infowindow.open(map, marker);
     });
     }
     </script>
</head>

<body onload="initialize()">              <!--바디 영역은 4 영역(헤더/메뉴/콘텐츠/풋터)으로 구성-->

<div id="header">                                           <!-- ch11 div#header 수정 -->
    <!-- 로고 -->
    <a href="/"><img src="{% static 'img/grandhotel_logo.jpg' %}" style="height:150px; display: block;  margin-left: 123%"/></a>
    <!-- user 객체는 장고 기본 객체이므로 모든 템플릿에서 사용 가능함 -->
    {% if user.is_active %} <!-- 로그인되면 user.is_active() 함수가 참을 반환-->
        <h4 class="welcome">환영합니다,
            <!-- firstof 태그는 뒤에 나오는 인자들 중에서 False 아닌 첫 인자를 선택함 -->
            <strong>{% firstof user.get_short_name user.get_username %}</strong>님. /
            <a href="{% url 'password_change' %}">비밀번호 변경</a> /
            <a href="{% url 'logout' %}">로그아웃</a>
        </h4>
    {% else %}
        <h4 class="welcome">환영합니다, 손님. /
            <a href="{% url 'login' %}">로그인</a> /
            <a href="{% url 'register' %}">회원가입</a>
        </h4>
    {% endif %}
</div>

<div id="menu">                     <!--메뉴 영역-->
    <li><a href="{% url 'bookmark:index' %}">제주 여행지</a></li>
    <li><a href="{% url 'blog:index' %}">이용 후기&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'login' %}">추가</a></li>
            <li><a href="{% url 'login' %}">편집</a></li>
        </ul>
    </li>
    <li><a href="{% url 'photo:index' %}">호텔 시설</a> <!-- ch10 수정 1/1-->
    </li>
    <li><a href="{% url 'blog:post_archive' %}">저장소</a></li>
    <li><a href="{% url 'blog:search' %}">검색</a></li>               <!--ch09 수정 1/1-->
    <li><a href="{% url 'admin:index' %}">관리자</a></li>
</div>

{% block content %}{% endblock %}   <!--블록 태그로 콘텐츠 영역 정의 -->

{% block footer %}{% endblock %}    <!--블록 태그로 풋터 영역 정의-->

<!--{% block js %}{% endblock js%}-->
</body>
</html>

templates/home.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}Grand Hotel{% endblock %}    <!--title 블록 재정의-->

<!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
{% load staticfiles %}
<!--extrastyle 블록을 재정의하여 추가적으로 home.css 연결-->
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}


{% block content %}                         <!--content 블록 재정의-->

<div id="content_home">     <!--content_home 영역 정의-->

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://www.suites.co.kr/upload/hotel/996330578.jpg">
    </div>

    <div class="item" >
      <img src="http://www.suites.co.kr/upload/hotel/412699785.jpg">
    </div>

      <div class="item">
      <img src="http://www.suites.co.kr/upload/hotel/463685927.jpg">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <hr style="border: solid 0.5px #609ab6;" />     <!--그림 및으로 5px 간격을 두고 수평선 넣기-->
</div>

    <!-- 구글 지도 넣기 -->
    <div class = "map_view">
    <h3 style="color: #447e9b" >오시는 길</h3><br/>
    <div id="map_view" style="width:300px; height:300px;"></div>
    <Br/>
        <hr style="border: solid 0.5px #609ab6;" />

    <div>
        <h3 style="color: #447e9b">글꼴과 컬러 소개</h3><br/>
        <p>- 컬러</p>
        <a href="/"><img src="{% static 'img/color.jpg' %}" style="width:20%; float:left"/></a><br/><br/>
        <p> 여러가지 색을 갖고 있는 제주의 바다처럼, <br/>글씨는 어두운 파란색들로, 배경색들은 <br/>옅은 하늘색과 민트색으로 표현했습니다.
            <br/>전체적인 배경은 깔끔함을 주기 위해 <br/>흰색으로 표현했습니다.
        </p>
        <br/>
        <p>- 글꼴</p>
        <a href="/"><img src="{% static 'img/font.jpg' %}" style="width:20%; float:left"/></a>
        <p> 가독성도 나쁘지 않고, 깔끔한 느낌을 주는, sunflower체를 사용했습니다.</p>

    </div>
    </div>

    <!-- 호텔 간략 소개 -->
    <div class = "info">
    <h3 style="color: #447e9b" >호텔 소개</h3><br/>
    <div>
        <a href="/"><img src="{% static 'img/sea.jpg' %}" style="width:50%; float:left"/></a><br/>
    </div>
    <div>
        <p style="font-size: 15px; color: #263755; text-style :bold; text-align: left">
        &nbsp;&nbsp; 북태평양의 푸른 바다와 한라산의 우아한<br/> &nbsp;&nbsp;자태를 뽐내는 환상의 섬, 제주도.<br/>
        &nbsp;&nbsp; 제주의 수려한 자연 경관과 아름다운 사람들이 <br/>&nbsp;&nbsp;한데 어울린
            제주 중문 단지 내 스위트호텔에서 <br/>&nbsp;&nbsp;삶의 여유를 즐기며 소중한 시간을 만드십시오.
            <br/>&nbsp;&nbsp;스위트호텔의 포근하고 아늑한 객실은 마치 집에 <br/>&nbsp;&nbsp;온 듯, 달콤하고 행복한 꿈을 가져다 주어<br/>
            &nbsp;&nbsp;고객 여러분의 여행을 더욱 가치 있게 만들어 드릴  <br/>&nbsp;&nbsp;것입니다.
            스위트호텔에서 편안한 여행의 즐거움을 <br/>&nbsp;만끽하시고 저희 호텔이 격조 높은 휴식처가 될 수 있도록
            &nbsp;저희 임직원들은 항상 정성이 깃든&nbsp;최고의 서비스를 제공하겠습니다.
        </p>
    </div>
        <Br/><br/><br/><br/>
        <h3 style="color: #447e9b">로고 소개</h3>
        <div>
            <a href="/"><img src="{% static 'img/grandhotel_logo.jpg' %}" style="width:20%; float:left"/></a><br/>
        </div>
        &nbsp;&nbsp;
        <div style = "margin-left: 180px">
            <p>따뜻한 제주에서만 볼 수 있는 야자수 나무를 가운데에 배치하고, <BR/>호텔의 이름인 GRAND HOTEL을 쓰고,
                <br/>배경은 부드러운 느낌을 주기 위해 연한 민트 색을 넣었습니다.</p>
        </div>
    </div>

</div>
{% endblock content %}

{% block footer %}                      <!--footer 블록 재정의-->
<div id="footer">
    &copy; Grand Hotel
</div>
{% endblock footer %}

templates/hometest.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}home.html{% endblock %}    <!--title 블록 재정의-->

{% block content %}                         <!--content 블록 재정의-->
    <div id="content">
        This is CONTENT area.
    </div>
{% endblock content %}

{% block footer %}                          <!--footer 블록 재정의-->
    <div id="footer">
        This is FOOTER area.
    </div>
{% endblock footer %}